#ENV QA
image:
  directory:
    event: images/events/
    profile: images/profiles/

spring:
  datasource:
    url: jdbc:h2:file:./data/demo
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

  #[5/9] seteo configuraciones del remitente del email
  # configuraciones del remitente del email
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${email}
    password: ${email_password}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#email de ejemplo para probar /resetPassword
mail: ${email_user_ejemplo}
